### ISSUE TITLE
`fidesctl generate-dataset` generates a dataset that fails validation

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#109]
### Overview
When using `generate-dataset` to bootstrap a dataset annotation, I'd expect the output file to successfully validate. However, when trying this locally using the latest pip version (0.9.6)... it doesn't.

### Steps to Reproduce
1. Run a local Postgres server with a basic test schema
2. Run `fidesctl -f config.toml generate-dataset postgresql://{user}:{password}@localhost:{port}/{database} postgres_example.yml`
3. Run `fidesctl -f config.toml apply --dry postgres_example.yml`
4. Expect no validation errors

### Actual Results
The dataset generated looks like this:
```
dataset:
- organizationId: 1
  fidesKey: postgres_example
  name: postgres_example
  description: 'Fides Generated Description for Dataset: postgres_example'
  datasetType: postgresql
  datasetLocation: localhost:6432
  datasetTables:
  - name: public.product
    description: 'Fides Generated Description for Table: public.product'
    datasetFields:
    - name: id
      description: 'Fides Generated Description for Column: id'
    - name: name
      description: 'Fides Generated Description for Column: name'
    - name: price
      description: 'Fides Generated Description for Column: price'
```

The validation errors looked like this:
```
(venv) ~/git/my-test-fides-project% fidesctl -f example_config.toml apply --dry postgres_example.yml
Loading resource manifests from postgres_example.yml
Failed to parse this resource: {'organizationId': 1, 'fidesKey': 'postgres_example',...} with the following errors:
2 validation errors for Dataset
location
  field required (type=value_error.missing)
fields
  field required (type=value_error.missing)
```
