### ISSUE TITLE
Allow delete-only SaaS endpoints

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#1184]
### Is your feature request related to a specific problem?

Some connector endpoints have delete requests without a corresponding read request. Using Rollbar as a concrete example, the people endpoint would be configured like this
```
- name: people
  requests:
    delete:
      method: POST
      path: /api/1/people/delete_jobs
      query_params:
        - name: email
          value: <email>
      headers:
        - name: X-Rollbar-Access-Token
          value: <write_access_token>
      param_values:
        - name: write_access_token
          connector_param: write_access_token
        - name: email
          identity: email
```
However, the missing `read` request for this endpoint means the delete would never be executed.

### Describe the solution you'd like

Allow a `delete` request to be configured for an endpoint without having to specify a `read` endpoint.

### Additional context

The legacy adaptors had a concept of `defaultData` for delete-only endpoints. I'm including this in case we want to take a look at other examples besides Rollbar.
```
defaultData:
  fields:
    - name: email
      source: email
      sourceType: IDENTITY
```
