### ISSUE TITLE
Allow multiple starting nodes for SaaS connector collection traversal

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#1198]
### Is your feature request related to a specific problem?

Some SaaS connector requests do not rely on any identity or dataset references to execute.

Example:
```
- name: conversations
  requests:
    read:
      method: GET
      path: /3.0/conversations
      query_params:
        - name: count
          value: 1000
        - name: offset
          value: 0
      param_values:
        - name: placeholder
          identity: email
      data_path: conversations
      pagination:
        strategy: offset
        configuration:
          incremental_param: offset
          increment_by: 1000
          limit: 10000
```
This request just needs to call `GET /3.0/conversations` with two query params that are defined inline. In order for this collection to be considered reachable by the Fidesops graph traversal, we added an artificial dependency on the `email` identity. This is even the workaround we provide in the [official documentation](https://ethyca.github.io/fidesops/saas_connectors/saas_config/#what-if-a-collection-has-no-dependencies).

### Describe the solution you'd like

In order to minimize the complexity of SaaS connector development we need to add this use-case to the Fidesops graph traversal to not consider such collections as unreachable or to be able to flag the collection as a "starting node" which does not have any dependencies.

### Describe alternatives you've considered, if any

Alternatively, we can just automatically add the artificial identity dependency for SaaS requests without `param_values` when parsing the SaaS config. This would avoid having to make core changes to Fidesops but it just seems like a shortcut to a more proper solution.
