### ISSUE TITLE
Remove the need for “primary_key” for SaaS connector delete endpoints

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#1199]
### Is your feature request related to a specific problem?

If a `delete` request is specified on a SaaS connector endpoint, it won't execute unless the associated dataset collection has one of its fields flagged with the `primary_key` fidesops_meta annotation.

Example:
```
delete:
  method: DELETE
  path: /api/v2/users/<user_id>.json
  param_values:
    - name: user_id
      references:
        - dataset: <instance_fides_key>
          field: users.id
          direction: from
```
```
collections:
  - name: users
    fields:
      - name: id
        data_categories: [system.operations]
        fidesops_meta:
          primary_key: True
          data_type: integer
```

### Describe the solution you'd like

Since this field is mostly applicable for database connectors, it would be ideal to eliminate this seemingly unrelated requirement for SaaS connectors, and prevent it from being another thing to watch out for during SaaS connector development.

### Additional context

The place where this check happens is at `graph_task.py`
```
@retry(action_type=ActionType.erasure, default_return=0)
def erasure_request(self, retrieved_data: List[Row], *inputs: List[Row]) -> int:
    """Run erasure request"""
    # if there is no primary key specified in the graph node configuration
    # note this in the execution log and perform no erasures on this node
    if not self.traversal_node.node.contains_field(lambda f: f.primary_key):
        logger.warning(
            "No erasures on %s as there is no primary_key defined.",
            self.traversal_node.node.address,
        )
        self.update_status(
            "No values were erased since no primary key was defined for this collection",
            None,
            ActionType.erasure,
            ExecutionLogStatus.complete,
        )
        return 0
```
