### ISSUE TITLE
Prompt user for required dataset references during SaaS connector configuration (BE)

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#1257]
### Is your feature request related to a specific problem?

The traversal for a some SaaS connectors cannot be initiated with just an email identity. Some connectors rely on user IDs that exist in other datasets (database or another SaaS connectors). Since the connector cannot run without these references, it is important to specify these requirements when the connector is instantiated.

### Describe the solution you'd like

A SaaS config should be able to specify a dataset reference placeholder for the user to configure when the other secrets are being input.
```
external_references:
  - name: uid
    description: Fullstory User ID

endpoints:
  - name: users
    requests:
      read:
        method: GET
        path: /users/v1/individual/<uid>
        headers:
          - name: Authorization
            value: Basic <access_token>
        param_values:
          - name: access_token
            connector_param: access_token
          - name: uid
            references: <uid>
```
