### ISSUE TITLE
Add ability to flag collections as "traversal_only"

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#1361]
### Is your feature request related to a specific problem?

There are instances when a collection is defined in a dataset only for the purposes of linking another collection to the rest of the traversal graph. In these cases, it's beneficial to mark a collection as being used for traversal only so data from this linking collection is not returned as part of a privacy request.

### Describe the solution you'd like

Add the ability to flag a collection as `traversal_only`. This use case originated from with with SaaS connectors so we're using Mailchimp as an example
```
- name: conversations
  traversal_only: True
  requests:
    read:
      method: GET
      path: /3.0/conversations
      query_params:
        - name: count
          value: 1000
        - name: offset
          value: 0
      param_values:
        - name: placeholder
          identity: email
      data_path: conversations
```
This collection would not be included in the Mailchimp dataset, but internally, Fidesops would merge the SaaS config and dataset to create this
```
dataset:
  - fides_key: mailchimp_example
    name: Mailchimp Dataset
    description: A sample dataset representing the Mailchimp connector for Fidesops
    collections:
      - name: messages
      ...
      - name: conversations
        fidesops_meta:
          traversal_only: True
```

### Describe alternatives you've considered, if any

We originally considered adding this as part of the policy but it makes more sense to configure this earlier in the workflow so we don't leak this information due to a misconfigured policy.

Using the flag name of `traversal_only` but we can go with something else if it makes more sense.
