### ISSUE TITLE
Data Map Excluding Systems Without Privacy Declarations

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#1414]
### Bug Description

If my System is not annotated with a privacy declaration, it is excluded from my datamap. I expect all of my available systems to be found on my datamap, regardless of their state of compliance (i.e. privacy declarations)

#### Steps to Reproduce

1. Create a System that does not have a privacy declaration
1. Export your data map (no system)
2. Add a privacy declaration
3. Export data map again (system is visible)

### Expected behavior

My datamap should contain all available resources, regardless of completeness. This is critical to being able to manage compliance via the datamap

### Screenshots

n/a

### Environment

* Version: 1.9.2
* OS: Darwin
* Python Version: 3.9.13
* Docker Version: 20.10.17

### Additional context

Originally discovered by @allisonking 

To be able to test this, adding a system like the following should work (note the `[]` under `privacy_declarations`, this is because `None` is not allowed):
```
system:
  # System Info
  - fides_key: fake_system
    name: fake system
    organization_fides_key: default_organization
    system_type: Service
    privacy_declarations: []
```

The main focus area to resolve this discrepancy I think should like in how we are [initially exporting records for a system](https://github.com/ethyca/fides/blob/3e48521afa21256c9c20590757dbb2fca9f022bc/src/fides/ctl/core/export.py#L177-L217) - having default values (or similar) should allow for the system to propagate to the exported data
