### ISSUE TITLE
Evaluation currently doesn't consider the hierarchy of type

### ISSUE THREAD

**Issue by earmenda** [ethyca/fides#149]
Splitting up issues from #88

data categories, data qualifiers and data uses have a parent_key which should be considered in evaluations. 

For example, if a policy rejects the `account` category, then it should also reject `account.contact.city`
```
data_category:
  - fides_key: account
    name: Account Data
    description: Data related to a system account.

  - fides_key: account.contact
    name: Account Contact Data
    parent_key: account
    description: Contact data related to a system account.

  - fides_key: account.contact.city
    name: Account City
    parent_key: account.contact
    description: Account's city level address data.
```
