### ISSUE TITLE
Remove the action field and add an "extra" inclusion enum

### ISSUE THREAD

**Issue by earmenda** [ethyca/fides#150]
Splitting up issues from #88

Right now it looks like we don't look at the action field in a policy rule. By default any rule created will be treated as a reject. Here is the enums we allow right now:

```
ACCEPT
REJECT
REQUIRE
```

We need to come up with a strategy for handling these

**Comment by ThomasLaPiana** [comment]
as a stop-gap we've left an "unimplemented" message in the codebase and will surface to the user if they try to use something other than "reject"

**Comment by ThomasLaPiana** [comment]
using the various `inclusion` options we have, `ANY/ALL/NONE` , i think this is already pretty possible and we should keep the default behavior as reject? reject becomes the default and we no longer have that field as an option, would that work?

**Comment by earmenda** [comment]
Currently we only accept `REJECT` as a valid option but it is not clear exactly what the behavior would be if we were to add `ACCEPT` and `REQUIRE` as options. These both require separate discussions I think.

`REQUIRE` was originally meant to be used as a way to kick off an approval workflow. This is beyond the scope of this issue so we will create the required issues to be able to support this. Here is the basics on what we would need to be able to have this functionality:
* Basic user authentication / authorization - #238
* Create UI for evaluation management #237
* Create approval workflow for evaluations that use REQUIRE. This still needs some thought as to how it would work exactly. It would be interesting to understand how it would work with a CI pipeline for instance. 

`ACCEPT` is odd because it conflicts with the idea of also having a `REJECT`. If you have policies that accept certain conditions then it's odd to also reject at the same time. One thought we had is that we could have taxonomies which either only use `ACCEPT` or only use `REJECT` policies. 

@ThomasLaPiana 
I'm not sure if I am thinking of this wrong but it still feels like there is use cases which the inclusion does not necessarily cover. What about a situation where you only want your systems to allow X category to be used for Y use and reject anything else in our datasets:

```
policy:
  - fides_key: policy_1
    rules:
      - name: only_allow_X_category
        description: Disallow any non-system data or uses.
        data_categories:
          inclusion: ANY
          values:
            - X
        data_uses:
          inclusion: ANY
          values:
            - Y
        data_subjects:
          inclusion: ANY
          values:
            - Z
        data_qualifier: qualifier
        action: ACCEPT
```

How would you define that using the inclusions `ALL`,`NONE` or `ANY`?

**Comment by ThomasLaPiana** [comment]
yeah thinking more about it, i think we are losing _some_ functionality there. maybe an easy way is to just check if it is `accept` or `reject` and then flip this statement accordingly?

https://github.com/ethyca/fides/blob/main/fidesctl/src/fidesctl/core/evaluate.py#L289

this would also allow us to flip it on a per-rule basis, meaning someone would use a broad `accept` to handle the majority of cases, and then a few specific `rejects` for edge-cases within the bounds of that accept

so a `reject` is `all()` (the current behaviour) and an `accept` flips it to `not all()`

**Comment by earmenda** [comment]
> yeah thinking more about it, i think we are losing _some_ functionality there. maybe an easy way is to just check if it is `accept` or `reject` and then flip this statement accordingly?
> 
> https://github.com/ethyca/fides/blob/main/fidesctl/src/fidesctl/core/evaluate.py#L289
> 
> this would also allow us to flip it on a per-rule basis, meaning someone would use a broad `accept` to handle the majority of cases, and then a few specific `rejects` for edge-cases within the bounds of that accept
> 


The conflict here would be that it is not clear which one takes priority. Does the `ACCEPT` override a `REJECT` or does a `REJECT` override an `ACCEPT`? One might feel more right than the other but I don't think this model make it clear. 

> so a `reject` is `all()` (the current behaviour) and an `accept` flips it to `not all()`

The logic wouldn't really work that simply anymore I don't think. `ACCEPT` evaluations could have conflicting evaluation decisions now even without a `REJECT`. With `REJECT` it was simple to evaluate whether a dataset had any violations without keeping any state. If two `REJECT` evaluations added violations for the same dataset then the result is the same, an evaluation failure. If you treat `ACCEPT` this way then the logic breaks down because one `ACCEPT` policy violation could be allowed by another `ACCEPT` policy. Let me know if that makes sense!

**Comment by ThomasLaPiana** [comment]
Yeah that does make sense, I think we should just declare that each rule needs to stand on its own then, and that state isn't shared between them. A rule is atomic and must pass/fail according to its own definition only, nothing takes precedence.

Due to that complexity then, maybe we can table the idea of adding "accept" and instead focus on how we can add similar functionality to what we have now. Maybe additional keywords for `inclusion` could help with this? Some kind of logic that says, "if anything other than these data categories exists in the privacy declaration, return true"

**Comment by ThomasLaPiana** [comment]
@earmenda the solution that just came to me is dropping the `accept` keyword and just adding an `EXTRA` option to the `InclusionEnum`, I think with that we could do the same thing functionally...

policy:
  - fides_key: policy_1
    rules:
      - name: only_allow_X_category
        description: Disallow any non-system data or uses.
        data_categories:
          inclusion: EXTRA # returns true if there are values in the declaration other than the values listed here
          values:
            - system
        data_uses:
          inclusion: EXTRA
          values:
            - provide
        data_subjects:
          inclusion: EXTRA
          values:
            - anonymous_user
        data_qualifier: aggregated
        action: REJECT

**Comment by ThomasLaPiana** [comment]
@earmenda does this make sense to you? instead of adding additional action words we should just add more inclusion words?

**Comment by earmenda** [comment]
@ThomasLaPiana this is a good way to go for this issue. I've been stuck on thinking of alternatives to `EXTRA` as the name is all. it doesn't feel obvious to me what that would mean as a user.

**Comment by ThomasLaPiana** [comment]
> @ThomasLaPiana this is a good way to go for this issue. I've been stuck on thinking of alternatives to `EXTRA` as the name is all. it doesn't feel obvious to me what that would mean as a user.

totally agreed, i even used a thesaurus 😂 

let's go ahead with this implementation then and we can think of a better name along the way

**Comment by earmenda** [comment]
@ThomasLaPiana 
The only concern I have with this one is that `all` and `any` feel analogous to each other and they determine how we interpret the collection of elements. `extra`(or whatever we call it) doesn't align well with what `inclusion` means in the context of that collection.

**Comment by ThomasLaPiana** [comment]
> @ThomasLaPiana The only concern I have with this one is that `all` and `any` feel analogous to each other and they determine how we interpret the collection of elements. `extra`(or whatever we call it) doesn't align well with what `inclusion` means in the context of that collection.

maybe we can change the "inclusion" name then? I always think of it like its described in the evaluation code itself:

`if the privacy declaration data categories have "<inclusion enum>" of the policy rule data categories, return True`

In this case i think it makes sense, because we're saying `if the privacy declaration data categories have extra data categories compared to the return policy rule data categories, return True`

**Comment by NevilleS** [comment]
After discussing I realize that `ONLY` works if you assume it's an accept rule (e.g. ACCEPT this system if it ONLY uses these categories), but since the rule is still going to be a REJECT we kinda need to figure out the opposite of ONLY. 

Here's a decent verb for this that works with the rest, I think: `OTHER`

Putting into practice...
* REJECT this system if `ANY` of these categories are used: `user.provided.identifiable.contact.email`, `user.provided.identifiable.contact.phone_number`
* REJECT this system if `ALL` of these categories are used together: `user.provided.identifiable.contact.email`, `user.provided.identifiable.contact.phone_number`
* REJECT this system if `OTHER` categories are used that are not: `user.provided.identifiable.contact.email`, `user.provided.identifiable.contact.phone_number`

**Comment by iamkelllly** [comment]
I think "OTHER" makes sense in the rejection scenario, but then are we saying that we'd not have "matches:OTHER" for another use case? 

Can someone confirm that my understanding is correct below? 

```yaml
policy:
  - fides_key: policy_1
    rules:
      - name: txn_msgs_only
        description: Allows use of phone number for transactional messaging only
        data_categories:
          matches: ANY 
          values:
            - user.provided.identifiable.contact.phone_number
        data_uses:
          matches: OTHER
          values:
            - provide.system.operations
            - provide.system.operations.support
        data_subjects:
          matches: ANY
          values:
            - customer
        data_qualifier: identified
        action: REJECT # this rule will reject the system if customer phone number is used for anything other than operations and support?
      - name: employee_data_use_prohibited
        description: Prevents usage of any employee identifiable data for anything other than workplace operations (workplace badge/biometric scanning, employer touchid consent for company app, HR ops, terms of employment)
        data_categories:
          matches: ANY 
          values:
            - user.derived.identifiable
            - user.provided.identifiable
        data_uses:
          matches: OTHER
          values:
            - provide.system.operations
            - collect
        data_subjects:
          inclusion: ANY
          values:
            - employee
        data_qualifier: identified
        action: ACCEPT # this rule will allow usage of any employee-provided or derived data to be used ONLY for collection and system operations?
```
