### ISSUE TITLE
Add a `database-coverage` command

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#161]
After thinking about some ways to reduce cognitive load on users, I think we need an _optional_ command that would allow users to verify that all of the fields in their databases are included in their dataset manifest files. This would then throw an automatic error when a user adds a dataset/collection/field but doesn't document it in their manifests

There are two possible options that I can think of for implementation here (please suggest other options as you think of them!):
1. user can pass a map of `{fides_key: database_url}` via the config/env vars
2. we could store these credentials (safely) within the API/db

I lean towards #1 from a design perspective, not to mention if we can avoid storing sensitive credentials in the db we should at all costs

**Example 1 for embedding the validation values into the TOML file**
```toml
[cli]
dataset_validation = {dataset_1 = "<database_url_1>", dataset_2 = "<database_url_2>"}
```

**Example 2 for embedding the validation values into the TOML file**
```toml
[datasets]
dataset_1 = "database_url_1"
dataset_2 = "database_url_2"
```
