### ISSUE TITLE
Code Climate coverage report not respecting coverage settings

### ISSUE THREAD

**Issue by sanders41** [ethyca/fides#2316]
Coverage is set in the `pyproject.toml` to ignore the `migrations` directory. When running the tests locally this setting is respected and the migrations doing so in the coverage report, but in code climate they are showing up as missing coverage.

```toml
[tool.coverage.run]
omit = ["src/fides/api/ctl/migrations/*"]
```
