### ISSUE TITLE
Git permissions error causing failing pipelines

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2440]
### Bug Description

Seeing workflow errors related to new git security upgrades on GHA runners.

### Additional context

https://github.com/actions/runner-images/issues/6775

**Comment by ThomasLaPiana** [comment]
According to the referenced issue, the fix should be something like:

```
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
```
