### ISSUE TITLE
Validate Endpoint does not support Foreign Key Traversal

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides#2476]
### Bug Description

When 
#### Steps to Reproduce

1. Create and validate the following dataset 
```
dataset:
  - fides_key: postgres_example_test_dataset
    name: Postgres Example Test Dataset
    description: Example of a Postgres dataset containing a variety of related tables like customers, products, addresses, etc.
    collections:
      - name: address
        fields:
          - name: city
            data_categories: [user.contact.address.city]
          - name: house
            data_categories: [user.contact.address.street]
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: state
            data_categories: [user.contact.address.state]
          - name: street
            data_categories: [user.contact.address.street]
          - name: zip
            data_categories: [user.contact.address.postal_code]

      - name: customer
        fields:
          - name: address_id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: address.id
                  direction: to
          - name: created
            data_categories: [system.operations]
          - name: email
            data_categories: [user.contact.email]
            fidesops_meta:
              identity: email
              data_type: string
          - name: id
            data_categories: [user.unique_id]
            fidesops_meta:
              primary_key: True
          - name: name
            data_categories: [user.name]
            fidesops_meta:
              data_type: string
              length: 40

      - name: employee
        fields:
          - name: address_id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: address.id
                  direction: to
          - name: email
            data_categories: [user.contact.email]
            fidesops_meta:
              identity: email
              data_type: string
          - name: id
            data_categories: [user.unique_id]
            fidesops_meta:
              primary_key: True
          - name: name
            data_categories: [user.name]
            fidesops_meta:
              data_type: string

      - name: login
        fields:
          - name: customer_id
            data_categories: [user.unique_id]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: customer.id
                  direction: from
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: time
            data_categories: [user.sensor]

      - name: orders
        fields:
          - name: customer_id
            data_categories: [user.unique_id]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: customer.id
                  direction: from
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: shipping_address_id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: address.id
                  direction: to

      # order_item
      - name: order_item
        fields:
          - name: order_id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: orders.id
                  direction: from
          - name: product_id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: product.id
                  direction: to
          - name: quantity
            data_categories: [system.operations]

      - name: payment_card
        fields:
          - name: billing_address_id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: address.id
                  direction: to
          - name: ccn
            data_categories: [user.financial.account_number]
          - name: code
            data_categories: [user.financial]
          - name: customer_id
            data_categories: [user.unique_id]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: customer.id
                  direction: from
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: name
            data_categories: [user.financial]
          - name: preferred
            data_categories: [user]

      - name: product
        fields:
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: name
            data_categories: [system.operations]
          - name: price
            data_categories: [system.operations]

      - name: report
        fields:
          - name: email
            data_categories: [user.contact.email]
            fidesops_meta:
              identity: email
              data_type: string
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: month
            data_categories: [system.operations]
          - name: name
            data_categories: [system.operations]
          - name: total_visits
            data_categories: [system.operations]
          - name: year
            data_categories: [system.operations]

      - name: service_request
        fields:
          - name: alt_email
            data_categories: [user.contact.email]
            fidesops_meta:
              identity: email
              data_type: string
          - name: closed
            data_categories: [system.operations]
          - name: email
            data_categories: [system.operations]
            fidesops_meta:
              identity: email
              data_type: string
          - name: employee_id
            data_categories: [user.unique_id]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: employee.id
                  direction: from
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: opened
            data_categories: [system.operations]

      - name: visit
        fields:
          - name: email
            data_categories: [user.contact.email]
            fidesops_meta:
              identity: email
              data_type: string
          - name: last_visit
            data_categories: [system.operations]
```

Then create and validate the following dataset and it will fail the validation step because it does not recognize the foreign key:

```
dataset:
  - fides_key: mongo_test
    name: Mongo Example Test Dataset
    description: Example of a Mongo dataset that contains 'details' about customers defined in the 'postgres_example_test_dataset'
    collections:
      - name: customer_details
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: customer_id
            data_categories: [user.unique_id]
            fidesops_meta:
              references:
                - dataset: postgres_example_test_dataset
                  field: customer.id
                  direction: from
          - name: gender
            data_categories: [user.gender]
            fidesops_meta:
              data_type: string
          - name: birthday
            data_categories: [user.date_of_birth]
            fidesops_meta:
              data_type: string
          - name: workplace_info
            fidesops_meta:
              data_type: object
            fields:
              - name: employer
                fidesops_meta:
                  data_type: string
              - name: position
                data_categories: [user.job_title]
                fidesops_meta:
                  data_type: string
              - name: direct_reports
                data_categories: [user.name]
                fidesops_meta:
                  data_type: string[]
          - name: emergency_contacts
            fidesops_meta:
              data_type: object[]
            fields:
              - name: name
                data_categories: [user.name]
                fidesops_meta:
                  data_type: string
              - name: relationship
                fidesops_meta:
                  data_type: string
              - name: phone
                data_categories: [user.contact.phone_number]
                fidesops_meta:
                  data_type: string
          - name: children
            data_categories: [user.childrens]
            fidesops_meta:
              data_type: string[]
          - name: travel_identifiers
            fidesops_meta:
              data_type: string[]
              data_categories: [system.operations]
          - name: comments
            fidesops_meta:
              data_type: object[]
            fields:
              - name: comment_id
                fidesops_meta:
                  data_type: string
                  references:
                    - dataset: mongo_test
                      field: conversations.thread.comment
                      direction: to
      - name: internal_customer_profile
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: customer_identifiers
            fields:
              - name: internal_id
                fidesops_meta:
                  data_type: string
                  references:
                    - dataset: mongo_test
                      field: customer_feedback.customer_information.internal_customer_id
                      direction: from
              - name: derived_emails
                data_categories: [user]
                fidesops_meta:
                  data_type: string[]
                  identity: email
              - name: derived_phone
                data_categories: [user]
                fidesops_meta:
                  data_type: string[]
                  return_all_elements: true
                  identity: phone_number
          - name: derived_interests
            data_categories: [user]
            fidesops_meta:
              data_type: string[]
      - name: customer_feedback
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: customer_information
            fields:
              - name: email
                fidesops_meta:
                  identity: email
                  data_type: string
              - name: phone
                data_categories: [user.contact.phone_number]
                fidesops_meta:
                  data_type: string
              - name: internal_customer_id
                data_categories: [system.operations]
                fidesops_meta:
                  data_type: string
          - name: rating
            data_categories: [user]
            fidesops_meta:
              data_type: integer
          - name: date
            data_categories: [system.operations]
            fidesops_meta:
              data_type: string
          - name: message
            data_categories: [user]
            fidesops_meta:
              data_type: string
      - name: flights
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: passenger_information
            fields:
              - name: passenger_ids
                fidesops_meta:
                  data_type: string[]
                  references:
                    - dataset: mongo_test
                      field: customer_details.travel_identifiers
                      direction: from
              - name: full_name
                data_categories: [user.name]
                fidesops_meta:
                  data_type: string
          - name: flight_no
          - name: date
          - name: pilots
            data_categories: [system.operations]
            fidesops_meta:
              data_type: string[]
          - name: plane
            data_categories: [system.operations]
            fidesops_meta:
              data_type: integer
      - name: conversations
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: thread
            fidesops_meta:
              data_type: object[]
            fields:
              - name: comment
                fidesops_meta:
                  data_type: string
              - name: message
                fidesops_meta:
                  data_type: string
              - name: chat_name
                data_categories: [user.name]
                fidesops_meta:
                  data_type: string
              - name: ccn
                data_categories: [user.financial.account_number]
                fidesops_meta:
                  data_type: string
      - name: employee
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: email
            data_categories: [user.contact.email]
            fidesops_meta:
              identity: email
              data_type: string
          - name: id
            data_categories: [user.unique_id]
            fidesops_meta:
              primary_key: True
              references:
                - dataset: mongo_test
                  field: flights.pilots
                  direction: from
          - name: name
            data_categories: [user.name]
            fidesops_meta:
              data_type: string
      - name: aircraft
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: planes
            data_categories: [system.operations]
            fidesops_meta:
              data_type: string[]
              references:
                - dataset: mongo_test
                  field: flights.plane
                  direction: from
          - name: model
            data_categories: [system.operations]
            fidesops_meta:
              data_type: string
      - name: payment_card
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: billing_address_id
            data_categories: [system.operations]
          - name: ccn
            data_categories: [user.financial.account_number]
            fidesops_meta:
              references:
                - dataset: mongo_test
                  field: conversations.thread.ccn
                  direction: from
          - name: code
            data_categories: [user.financial]
          - name: customer_id
            data_categories: [user.unique_id]
          - name: id
            data_categories: [system.operations]
            fidesops_meta:
              primary_key: True
          - name: name
            data_categories: [user.financial]
          - name: preferred
            data_categories: [user]
      - name: rewards
        fields:
          - name: _id
            fidesops_meta:
              primary_key: True
              data_type: object_id
          - name: owner
            fidesops_meta:
              data_type: object[]
              return_all_elements: true
            fields:
              - name: phone
                data_categories: [user.contact.phone_number]
                fidesops_meta:
                  data_type: string
                  references:
                    - dataset: mongo_test
                      field: internal_customer_profile.customer_identifiers.derived_phone
                      direction: from
              - name: shopper_name
          - name: points
            fidesops_meta:
              data_type: integer
          - name: expiration_date
```

### Expected behavior

It successfully validates and detects the other keys in the graph 

### Environment

* Version: 2.5.1-encoders
* OS: OSX Intel

### Additional context

https://ethyca.slack.com/archives/CBKK8TS74/p1675292332168889
