### ISSUE TITLE
Create a new docker-compose file for fides_env(test) that does not mount a volume

### ISSUE THREAD

**Issue by sanders41** [ethyca/fides#2503]
### Is your feature request related to a specific problem?

In testing we found that running `nox -s "fides_env(test)"` with a volume mount for fides can cause unexpected results (specifically we saw this with the `ui-build` directory. It would be good to start `nox -s "fides_env(test)"` with a separate `docker-compose` file that does not contain the volume mount to ensure no dev files are impacting testing.

### Describe the solution you'd like

Create a new `docker-compose` file that removes the volume mount lines from `fides`

```yaml
    volumes:
      - type: bind
        source: .
        target: /fides
        read_only: False
```

### Describe alternatives you've considered, if any

Keep things like they are.

### Additional context

_Add any other context or screenshots about the feature request here._
