### ISSUE TITLE
More CI references and potentially reorganization of the CI references page

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#262]
Some additional CI reference tools that we want to consider validating our current references against or adding to the list of reference CI tools that fidesctl can integrate with. 
* AWS Codepipeline
* Azure Pipelines
* Bitbucket
* Bamboo
* Team City
* (if anyone's heard of "Git Runner", that would be on this list too but i can't confirm its existence so it's on hold)

For ease of searchability, we want to verify and at least include mention of the different tools in the [CI Reference documentation](https://ethyca.github.io/fides/ci_reference/). The reference documentation may be so similar across tools (spoiler, they are similar) that it probably a waste to list every single CI tool as an H2 on the docs!

**Comment by ThomasLaPiana** [comment]
@iamkelllly in theory fidesctl can work with _any_ CI tool, is the main thing here just to make sure we explicitly list these CI tools so that users visiting the site looking for CI guidance for them are more likely to find it?

**Comment by RobertKeyser** [comment]
@ThomasLaPiana or @iamkelllly has anyone started this? I don't want to step on any toes if I commit what I have for Azure DevOps Pipelines. (I'd probably rework the triggers and such to match our other formatting if I actually commit it)

#### CI

```yaml
trigger:
  - main

jobs:
  - job: "Fides_Privacy_as_Code"
    pool:
      vmImage: ubuntu-latest
    container:
      image: ethyca/fidesctl:1.3.1
    steps:
      - checkout: self
      - script: fidesctl evaluate --dry .fides/
        displayName: "Fidesctl Dry Evaluation"
```

#### CD

```yaml
trigger: none
resources:
  pipelines:
    - pipeline: CD
      source: CI
      trigger:
        branches:
          include:
            - main

jobs:
  - job: "Fides_Privacy_as_Code"
    pool:
      vmImage: ubuntu-latest
    container:
      image: ethyca/fidesctl:1.3.1
    steps:
      - checkout: self
      - script: fidesctl evaluate .fides/
        displayName: "Fidesctl Evaluation"
```
