### ISSUE TITLE
Move migrations to a CLI command/API endpoint instead of happening automatically

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#3093]
### Is your feature request related to a specific problem?

As the title states, while sometimes convenient it is also potentially very dangerous or inconvenient to _always_ run migrations on server start.

We should make this functionality configurable, and add a `fides db migrate` CLI command + admin endpoint

#### New `fides.toml` option

```toml
[database]
automigration = false # The server will not run initialization steps and will instead require the user to run 'fides db migrate'
```
