### ISSUE TITLE
[Spike] Dataset field differentiation

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#3612]
### Bug Description

This particular issue is in the grey area between a "bug" and a "feature". When handling a dataset where there are two fields, with the same category of PII, they will be treated as though they are under the same identity for access and erasure purposes.

For example in a collection like

```
import mongoose from "mongoose";

const User = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },
});

const Gift = new mongoose.Schema({
    toUser: User,
    fromUser: User,
});

```

the dataset:

```
fides_key: example_dataset
name: MongoDB Atlas
collections:
  - name: gifts
    fields:
      - name: _id
        fidesops_meta:
          data_type: object_id
          primary_key: True
      - name: toUser
        fidesops_meta:
          data_type: object
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: example_dataset
                  field: users._id
                  direction: from
              data_type: object_id
          - name: name
            data_categories: [user.denormalized]
            fidesops_meta:
              data_type: string
      - name: fromUser
        fidesops_meta:
          data_type: object
        fields:
          - name: _id
            data_categories: [system.operations]
            fidesops_meta:
              references:
                - dataset: example_dataset
                  field: users._id
                  direction: from
              data_type: object_id
          - name: name
            data_categories: [user.denormalized]
            fidesops_meta:
              data_type: string

  - name: users
    fields:
      - name: _id
        fidesops_meta:
          data_type: object_id
          primary_key: True
      - name: name
        data_categories: [user.name]
        fidesops_meta:
          data_type: string

```

will return `fromUser.firstName` fields when only `toUser`'s related `users._id` matches.

### Expected behavior

The fields can stay the same data category, and Fides would only target the `User` object that matches the related ID.
