### ISSUE TITLE
Null object incorrectly overwritten with masked value

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#3905]
### Bug Description

The output of `query_config.update_value_map` generates an incorrect value map for a null object field. The `string` value of "MASKED" generated by `query_config` is not compatible with the expected data type of `object`.

**Current output**
`{"shipping": "MASKED"}`

**Expected output**
Empty map `{}` 

### Steps to Reproduce

**Minimal dataset**
```
collections:
  - name: customer
    fields:
      - name: shipping
        fields:
          - name: address
            fields:
              - name: city
                data_categories: [user.contact.address.city]
                fidesops_meta:
                  data_type: string                  
          - name: name
            data_categories: [user.name]
            fidesops_meta:
              data_type: string
          - name: phone
            data_categories: [user.contact.phone_number]
            fidesops_meta:
              data_type: string
```

**Data to mask**
```
{
  "shipping": null
}
```

A policy targeting `user.name` fields

### Additional context
This was discovered in the Stripe connector. The item returned for the `customer` collection contains a null `shipping` field. If the `shipping` field were populated, Fides would attempt to mask the nested `name` field. In this case the object field is null so we shouldn't generate any values to replace this null field value.
