### ISSUE TITLE
data_responsibility_title being serialized with python type definition

### ISSUE THREAD

**Issue by earmenda** [ethyca/fides#458]
### Bug Description

Serialization of data_responsibility_title is including an ugly python type `!!python/object/apply:fideslang.models.DataResponsibilityTitle` 

```
root@7da6bfd30c0d:/fides/fidesctl# fidesctl generate system aws manifest.yml

Generated system manifest written to manifest.yml
root@7da6bfd30c0d:/fides/fidesctl# 
root@7da6bfd30c0d:/fides/fidesctl# cat manifest.yml 
system:
- fides_key: redshift-cluster-1
  organization_fides_key: default_organization
  name: redshift-cluster-1
  description: 'Fides Generated Description for Redshift Cluster: redshift-cluster-1'
  fidesctl_meta:
    resource_id: arn:aws:redshift:us-east-1:658462651023:namespace:6ac37ac8-4546-4883-8da5-066a658f5d3d
    endpoint_address: redshift-cluster-1.cohs2e5eq2e4.us-east-1.redshift.amazonaws.com
    endpoint_port: '5439'
  system_type: redshift_cluster
  data_responsibility_title: !!python/object/apply:fideslang.models.DataResponsibilityTitle
  - Controller
  privacy_declarations: []
  administrating_department: Not defined
  data_protection_impact_assessment:
    is_required: false
```

#### Steps to Reproduce

`fidesctl generate system aws manifest.yml`

### Expected behavior

`data_responsibility_title: Controller`
