### ISSUE TITLE
Protocol gets doubled when using the server_url from the generated fidesctl.toml file

### ISSUE THREAD

**Issue by sanders41** [ethyca/fides#512]
### Bug Description

When generating the `fidesctl.toml` file with `fidesctl init` the `server_url` that gets generated is `http://localhost`. Then subsequent uses of the file results in an error because `server_protocol` is appended to the `server_url` resulting in `http://http://fidesctl`

#### Steps to Reproduce

1. Run `fidesctl init`
1. Run `docker-compose run --rm fidesctl /bin/bash` with the following docker-compose file
1. Run `fidesctl status` in the docker container.

```yaml
services:
  fidesctl:
    image: ethyca/fidesctl:lateset
    command: fidesctl webserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      fidesctl-db:
        condition: service_healthy
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - FIDESCTL__CLI__SERVER_HOST=http://fidesctl
      - FIDESCTL__CLI__SERVER_PORT=8080
      - FIDESCTL__API__DATABASE_URL=postgres:fidesctl@fidesctl-db:5432/fidesctl
    volumes:
      - type: bind
        source: ./.fides/ # Update this to be the path of your .fides/ folder
        target: /fides/.fides/
        read_only: False

  fidesctl-db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-fidesctl:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fidesctl
      - POSTGRES_DB=fidesctl

volumes:
  postgres-fidesctl:
```

### Expected behavior

The URL should only contain `http://` once.

### Screenshots

![Screenshot from 2022-04-24 14-05-39](https://user-images.githubusercontent.com/25045024/164990234-649a46ce-cca5-43e6-b54b-85081bd6db4f.png)

### Environment

* Version: latest docker image
* OS: Linux
* Python Version: 3.8
* Docker Version: 20.10.14

### Additional context

When running `fidesctl init` the `server_url` is generated with [this validator](https://github.com/ethyca/fides/blob/f780ee8529648525f1d5d3c943e6ff4aa950cdae/src/fidesctl/core/config/cli_settings.py#L23) which concatenates the `server_protocol` and `server_host` resulting in `http:localhost` in the `fidesctl.toml` file resulting in the the following config for the cli.

```toml
[cli]
analytics_id = "d364070208d491fe88fe0309cce6d509"
server_url = "http://localhost"
```

From the test files it looks like the expected output is something like:

```toml
[cli]
server_host = "fidesctl"
server_port = 8080
```

And an example of an invalid config as:

```toml
[cli]
server_host = "http://invalid"
server_port = "8080"
```

So it looks like the expected is both to have a `server_host` instead of a `server_url` and for the URL to not contain the `http://`?
