### ISSUE TITLE
Add fidescls context classifications to `annotate` via the fidescls python package

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#515]
### Is your feature request related to a specific problem?

Fidesctl needs the ability to import fidescls as a python package and use its model to attempt to automatically annotate datasets.

### Describe the solution you'd like

Add `fidescls` as an optional dependency to fidesctl. Inject the fidescls model into the `annotate` workflow to provide contextual classification suggestions.

### Describe alternatives you've considered, if any

Spinning up the fidescls model as a server. This is heavier than what we want

### Additional context

To keep things small, this only needs to handle context. Content will come in another issue

**Comment by brentonmallen1** [comment]
I had a tutorial call with Adrian and walked through what it would be like to use fidescls as a python module. A recording of the call is captured here: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2262990932/2022-04-12+-+fidescls+as+python+module+overview

Might have to scrub a bit through the video to get to the relevant part but there might still be good context in there.  Let me know if there are any questions about it.

**Comment by ThomasLaPiana** [comment]
given that fidescls needs access to the database, this might actually need to happen in `generate`, since `annotate` currently has no knowledge of the database. Maybe this looks like adding an `--annotate` flag to the `generate` command?

**Comment by brentonmallen1** [comment]
I can see it being available at in the annotate use case as a ease of use thing, but that could always be added upon request/feedback from the user.  Unless product thinks otherwise regarding the customer's needs.

Doing an `annotate` during the `generate` process, might be a bit cumbersome if we're asking the user for input while traversing their database (depends on implementation).  I could see a low-effort path being something like auto-injecting x results from classify into the dataset.yml files as comments, which I think we briefly discussed at one point.

**Comment by ThomasLaPiana** [comment]
> I can see it being available at in the annotate use case as a ease of use thing, but that could always be added upon request/feedback from the user. Unless product thinks otherwise regarding the customer's needs.
> 
> Doing an `annotate` during the `generate` process, might be a bit cumbersome if we're asking the user for input while traversing their database (depends on implementation). I could see a low-effort path being something like auto-injecting x results from classify into the dataset.yml files as comments, which I think we briefly discussed at one point.

hmmmm that would make it dangerously easy to accidentally commit sensitive PII to git though, as an engineer I wouldn't be comfortable with that at all as human error is just too common around that stuff.

For `generate --annotate` i was thinking we wouldn't actually consult the user. Fidescls would auto-populate every single field and the user could then go back and audit the fields themselves if they wanted to.

**Comment by brentonmallen1** [comment]
I'm not sure I understand the `accidentally commit sensitive PII to git` bit, and maybe it's worth talking about in office hours, but I didn't see PII being recorded/stored anywhere (outside of RAM during the process).

I can see 2 issues with not consulting a user and auto injecting:

1)  At least until they can have a view into performance metrics, and/or choose their risk tolerance by some mechanism is that we're asking people to trust us and I don't think we'll have earned that - meaning I can see people being hesitant to use it

2) If we make it so the user has to check the classifier's work, are we still lowering the barrier of entry?

@iamkelllly do we have any customer perspective on this?

**Comment by ThomasLaPiana** [comment]
@brentonmallen1 i misunderstood what you had said previously, you said `auto-injecting x results` and i assumed you meant the raw data, not the annotation suggestions. that makes way more sense!

Your two points are conflicting it seems, what is the difference between consulting the user at runtime vs. asking them to look over the file after it is generated? Either way we're telling them not to trust the classifier

**Comment by brentonmallen1** [comment]
ah, I thought that might have been it. I should have been more explicit.


> Your two points are conflicting it seems, what is the difference between consulting the user at runtime vs. asking them to look over the file after it is generated? 

I can see that, I think, to me, the difference is async vs sync annotation.  At-runtime is interactive and requires upfront time investment and auto-inject as comments can be audited async.  Then again there is the intermediate saving features of annotate 🤔 .  Not sure if there would be implications when dealing with sampling from the dataset when doing content classification.

> Either way we're telling them not to trust the classifier

It seemed like the suggestion was to auto populate the data categories, which I guess we'd have to express that they double check things in the documentation pretty adamantly.  I think my main concern with auto inserting data categories (not as comments) means that those data categories become part of the taxonomy and 'consumable by fides'.  This might encourage someone to not look at them thoroughly enough.

**Comment by iamkelllly** [comment]
Wanted to chime in here with a usability and product opinion on this. To be very clear, our goal with this is to:
1) reduce level of manual effort for any user of fidesctl to create/annotate a dataset  AND
2) reduce cognitive load for the user to create/annotate a dataset. 

imo, by default, the annotations need to be auto-injected into the generated dataset yaml, this helps achieve (1), but i think @brentonmallen1 is correct in assuming that the user hasn't really gained trust in the classification and yes we are, in fact, telling them to not trust the classifier 😄  Counterintuitive, I know, but a user cannot gain trust in completely "hands off" ML classification without looking at how it classified the data first (seeing is believing, after all!). 

To achieve goal (2), I think there's a few different options we can do here that still keep (1) intact: 
a) *Low confidence recommendations in comments*: user does `generate dataset` and it generates yaml file, auto-injects data category directly into yaml, with in-line comments of the top-n (i recommend 3) next confident matches.
![Screen Shot 2022-04-27 at 11 27 14 AM](https://user-images.githubusercontent.com/85575406/165554505-d2a8fdde-2130-46ce-a471-a8a8ddaebaa5.png)

```yaml
...
    fields:
    - name: id
      description: 'Fides Generated Description for Column: id'
      data_categories: [user.provided.identifiable.email]
      data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified
    - name: name
      description: 'Fides Generated Description for Column: name'
      data_categories: [user.provided.identifiable.name] #{'label':'user.provided.identifiable.credentials.password', 'score':'0.697'}, {'label':'user.provided.identifiable.device.device_id', 'score':'0.587'}
      data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified
...
```

b) *User-specified confidence threshold*: user passes optional argument indicating performance score to exceed in order to be auto-injected, next 3 options will be inserted as in-line comments
![Screen Shot 2022-04-27 at 11 27 34 AM](https://user-images.githubusercontent.com/85575406/165554595-b62dc40e-25ad-4a36-aef4-350d7d7aef05.png)
```yaml
...
    fields:
    - name: id
      description: 'Fides Generated Description for Column: id'
      data_categories: [] #{'label':'user.provided.identifiable.device.device_id', 'score':'0.587'}
      data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified
    - name: name
      description: 'Fides Generated Description for Column: name'
      data_categories: [user.provided.identifiable.name] #{'label':'user.provided.identifiable.credentials.password', 'score':'0.697'}, {'label':'user.provided.identifiable.device.device_id', 'score':'0.587'}
      data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified
...
```

c) *Optional flag for manual reconciliation*: since we are _defaulting_ to automatically classifying, we allow the user to provide an optional flag to indicate that they want to manually reconcile the results, where we write it to a yaml file of their choosing.
![Screen Shot 2022-04-27 at 11 29 58 AM](https://user-images.githubusercontent.com/85575406/165555127-fbacfd86-316b-44ba-96a8-bda5b496114e.png)

```yaml
...
    fields:
    - name: id
      description: 'Fides Generated Description for Column: id'
      data_categories: [] #{'label':'user.provided.identifiable.email', 'score':'0.871'}, {'label':'user.provided.identifiable.device.device_id', 'score':'0.587'}
      data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified
    - name: name
      description: 'Fides Generated Description for Column: name'
      data_categories: [] # {'label':'user.provided.identifiable.name', 'score':'0.997'},{'label':'user.provided.identifiable.credentials.password', 'score':'0.697'}, {'label':'user.provided.identifiable.device.device_id', 'score':'0.587'}
      data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified
...
```
