### ISSUE TITLE
Update "Running Fidesctl in Docker" guide to include a version tag

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#680]
### Docs Update Description

If you follow the guide here: https://ethyca.github.io/fides/1.6.0/quickstart/docker/

You'll set up a compose file like:
```
services:
  fidesctl:
    image: ethyca/fidesctl
    command: fidesctl webserver
...
```

However, it looks when you do this, Docker defaults to looking for that image locally, resulting in this error:
```
Creating network "fides_default" with the default driver
Creating volume "fides_postgres" with default driver
Pulling fidesctl-db (postgres:12)...
12: Pulling from library/postgres
214ca5fb9032: Pull complete
...
Digest: sha256:742e8c57aaa18bf60076b959ea3e7c7aa118a963eca0a0d6b3daefe7bbbc0e8d
Status: Downloaded newer image for postgres:12
Pulling fidesctl (ethyca/fidesctl:local)...
ERROR: manifest for ethyca/fidesctl:local not found: manifest unknown: manifest unknown
```

This is probably documented somewhere in the Docker docs, but the fix for this is to specify an image which forces Docker to correctly pull from our DockerHub, like:
```
services:
  fidesctl:
    image: ethyca/fidesctl:1.6.0
    command: fidesctl webserver
```

Maybe we want to set that to `:latest` or whatnot, but you know what I mean!
